# Generated by Django 3.0.2 on 2020-09-15 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=10, unique=True)),
                ('class_seating_capacity', models.IntegerField()),
                ('class_weblecture_support', models.BooleanField()),
            ],
            options={
                'db_table': 'classroom',
            },
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'shape',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=20)),
                ('student_DOJ', models.DateTimeField(auto_now_add=True)),
                ('student_standard', models.CharField(max_length=8)),
                ('student_rollno', models.IntegerField(unique=True)),
                ('student_ranking', models.IntegerField()),
                ('class_student', models.ManyToManyField(related_name='class_Students', to='school.Classroom')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=10, unique=True)),
                ('subject_chapters', models.IntegerField()),
                ('subject_total_duration', models.IntegerField()),
                ('subject_per_class_duration', models.IntegerField()),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=10)),
                ('teacher_DOJ', models.DateTimeField(auto_now_add=True)),
                ('teacher_salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('classroom', models.ManyToManyField(related_name='class_Teachers', to='school.Classroom')),
                ('subject', models.ManyToManyField(related_name='subject_Teachers', to='school.Subject')),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='StudentRelative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_relative_name', models.CharField(max_length=20)),
                ('student_relative_phone_number', models.CharField(max_length=10, unique=True)),
                ('student_relative_type', models.CharField(max_length=10)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Relatives', to='school.Student')),
            ],
            options={
                'db_table': 'student_relative',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='subject_student',
            field=models.ManyToManyField(related_name='subject_Students', to='school.Subject'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='class_shape_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Shapes', to='school.Shape'),
        ),
    ]
