# Generated by Django 3.0.2 on 2020-09-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='subject_student',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_teachers',
        ),
        migrations.AddField(
            model_name='student',
            name='subject_student',
            field=models.ManyToManyField(related_name='subject_Students', to='school.Subject'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject_teachers',
            field=models.ManyToManyField(related_name='subject_Teachers', to='school.Subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_per_class_duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_total_duration',
            field=models.IntegerField(),
        ),
    ]
