# Generated by Django 3.0.2 on 2020-09-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20200915_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_name',
            field=models.CharField(max_length=20),
        ),
    ]
