# Generated by Django 3.0.2 on 2020-09-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20200913_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='studentrelative',
            name='student_relative_name',
            field=models.CharField(max_length=20),
        ),
    ]
