# Generated by Django 3.0.2 on 2020-09-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20200916_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
