# Generated by Django 3.0.2 on 2020-09-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20200916_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_DOJ',
            field=models.DateTimeField(),
        ),
    ]
